
GRANT USAGE ON DATABASE cdm_datalake TO ROLE omop_elt;
GRANT USAGE ON SCHEMA cdm_datalake.gpc to ROLE omop_elt;
GRANT SELECT ON ALL TABLES IN SCHEMA CDM_DATALAKE.GPC TO ROLE omop_elt;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CDM_DATALAKE.GPC TO ROLE omop_elt;

GRANT SELECT ON ALL VIEWS IN SCHEMA CDM_DATALAKE.GPC TO ROLE omop_elt;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CDM_DATALAKE.GPC TO ROLE omop_elt;
