version: '3.5'

services:

  ohdsi-atlas:
    image: ohdsi-atlas:latest
    build:
      context: ./Atlas
      args:
        - WEBAPI_URL=${WEBAPI_URL}
    container_name: ohdsi-atlas
    environment: 
      - WEBAPI_URL=${WEBAPI_URL}
    ports:
      - "80:8080"
    depends_on:
      - ohdsi-webapi

  ohdsi-webapi:
    image: ohdsi-webapi:latest
    build: 
      context: ./WebAPI
      args:
        - GIT_BRANCH=${GIT_BRANCH}
        - ATLAS_URL=${ATLAS_URL}
        - WEBAPI_URL=${WEBAPI_URL}
        - WEBAPI_DB=${WEBAPI_DB}
        - WEBAPI_DB_username=${WEBAPI_DB_username}
        - WEBAPI_DB_password=${WEBAPI_DB_password}
        - WEBAPI_SCHEMA=${WEBAPI_SCHEMA}
        - SECURITY_PROVIDER=${SECURITY_PROVIDER}
        - SECURITY_ORIGIN=${SECURITY_ORIGIN}
        - SSL_ENABLED=${SSL_ENABLED}
    container_name: ohdsi-webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres-webapi

  postgres-webapi:
    image: postgres-webapi:latest
    container_name: postgres-webapi
    build:
      context: ./postgres-webapi
    environment:
      - POSTGRES_USER=mhmcb
      - POSTGRES_PASSWORD=Password123
    volumes:
      - postgres-webapi-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  postgres-cdm:
    image: postgres-cdm:latest
    container_name: postgres-cdm
    build:
      context: ./postgres-cdm
    environment:
      - POSTGRES_USER=mhmcb
      - POSTGRES_PASSWORD=Password123
    volumes:
      - postgres-cdm-vol:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mhmcb@missouri.edu
      - PGADMIN_DEFAULT_PASSWORD=Password123
    logging:
      driver: none

volumes:
  postgres-cdm-vol:
    name: postgres-cdm-vol
  postgres-webapi-vol:
    name: postgres-webapi-vol

