version: '3.5'

services:

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mhmcb@missouri.edu
      - PGADMIN_DEFAULT_PASSWORD=Password123
    logging:
      driver: none
