CREATE TABLE {{ cdm_db }}.{{ cdm_schema }}.device_exposure (
  device_exposure_id integer NOT NULL,
  person_id integer NOT NULL,
  device_concept_id integer NOT NULL,
  device_exposure_start_date date NOT NULL,
  device_exposure_start_datetime TIMESTAMP NULL,
  device_exposure_end_date date NULL,
  device_exposure_end_datetime TIMESTAMP NULL,
  device_type_concept_id integer NOT NULL,
  unique_device_id varchar(255) NULL,
  production_id varchar(255) NULL,
  quantity integer NULL,
  provider_id integer NULL,
  visit_occurrence_id integer NULL,
  visit_detail_id integer NULL,
  device_source_value varchar(50) NULL,
  device_source_concept_id integer NULL,
  unit_concept_id integer NULL,
  unit_source_value varchar(50) NULL,
  unit_source_concept_id integer NULL
) AS
SELECT
  NULL AS device_exposure_id,
  NULL AS person_id,
  NULL AS device_concept_id,
  NULL AS device_exposure_start_date,
  NULL AS device_exposure_start_datetime,
  NULL AS device_exposure_end_date,
  NULL AS device_exposure_end_datetime,
  NULL AS device_type_concept_id,
  NULL AS unique_device_id,
  NULL AS production_id,
  NULL AS quantity,
  NULL AS provider_id,
  NULL AS visit_occurrence_id,
  NULL AS visit_detail_id,
  NULL AS device_source_value,
  NULL AS device_source_concept_id,
  NULL AS unit_concept_id,
  NULL AS unit_source_value,
  NULL AS unit_source_concept_id
WHERE 1=0;
