-- GRANT ALL ON SCHEMA
GRANT ALL ON ALL SCHEMAS IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;

GRANT ALL ON ALL TABLES IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE TABLES IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;
