-- GRANT ALL ON SCHEMA
GRANT ALL ON ALL SCHEMAS IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;

GRANT ALL ON ALL TABLES IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE TABLES IN DATABASE {cdm_db} TO ROLE OMOP_ATLAS;

use database {cdm_db};
use schema {cdm_schema};
drop view CARE_SITE;
drop view CONDITION_ERA;
drop view CONDITION_OCCURRENCE;
drop view DEATH;
drop view DRUG_EXPOSURE;
drop view LOCATION;
drop view MEASUREMENT;
drop view OBSERVATION;
drop view OBSERVATION_PERIOD;
drop view PERSON;
drop view PROCEDURE_OCCURRENCE;
drop view PROVIDER;
drop view VISIT_OCCURRENCE;