setwd("~/Desktop/Repositories/OMOP_ON_P_CDM/OMOP_ON_PCORNET_CDM")
options(connectionObserver = NULL)
options(useFancyQuotes = FALSE)

library(DatabaseConnector)
library(SqlRender)
library(Achilles)
library(DataQualityDashboard)
library(AresIndexer)
library(keyring)
options(connectionObserver = NULL)

aresDataRoot <- "./output/data"

cdmDatabaseSchema = "cdm"
resultsDatabaseSchema = "results" # used to store Achilles output
vocabDatabaseSchema = "cdm" #usually located within the cdm schema
numThreads = 4
cdmSourceName = 'MU'
cdmVersion = "5.4"

# Build JDBC connection string
CONNECTION_STRING <- paste0(
  "jdbc:snowflake://", "TKNLTGA-I2B2DB", 
  ".snowflakecomputing.com/?db=", "atlas_mu_prod",
  "&schema=", "RESULTS",
  "&warehouse=", "OMOP_ETL_WH", 
  "&role=", "OMOP_ELT", 
  "&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true",
  "&private_key_file=", "./env/deidentified/rsa_key.p8",
  "&private_key_file_pwd=", ""
)

# CONNECTION_STRING <- paste0(
#   "jdbc:snowflake://", "TKNLTGA-XP02744", 
#   ".snowflakecomputing.com/?db=", "OMOP_CDM",
#   "&schema=", "RESULTS",
#   "&warehouse=", "ATLAS_WH", 
#   "&role=", "OMOP_ELT", 
#   "&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true",
#   "&private_key_file=", "./env/identified/rsa_key.p8",
#   "&private_key_file_pwd=", ""


keyring::key_set_with_value("connectionString", password = CONNECTION_STRING)
keyring::key_set_with_value("user", password = "ATLAS_ETL_USER")
keyring::key_set_with_value("password", password = "")

# Create connection details directly using credentials
connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = "snowflake", 
  server = "",
  connectionString = keyring::key_get("connectionString"),
  user = keyring::key_get("user"),
  password = keyring::key_get("password"),
  pathToDriver = "./drivers/"
)


releaseKey <- AresIndexer::getSourceReleaseKey(connectionDetails, cdmDatabaseSchema)
datasourceReleaseOutputFolder <- file.path(aresDataRoot, releaseKey)


# Run Achilles
Achilles::achilles(
  connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema ,
  resultsDatabaseSchema= resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  numThreads = numThreads,
  cdmVersion = cdmVersion,
  createIndices = F,
  createTable = T,
  smallCellCount = 0
)

#Run data quality checks
tablesToExclude <- c("COHORT_DEFINITION","CONCEPT", "VOCABULARY", "CONCEPT_ANCESTOR", "CONCEPT_RELATIONSHIP", "CONCEPT_CLASS", "CONCEPT_SYNONYM", "RELATIONSHIP", "DOMAIN")
DataQualityDashboard::executeDqChecks(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  cdmSourceName = cdmSourceName,
  numThreads = numThreads,
  outputFolder = datasourceReleaseOutputFolder,
  outputFile = "dq-result.json",
  verboseMode = T,
  writeToTable = F,
  tablesToExclude = tablesToExclude,
  cdmVersion = cdmVersion

)


# Export Achilles results to Ares supported format
Achilles::exportToAres(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  outputPath = aresDataRoot
)

# Run Achilles temporal characterization
outputFile <- file.path(datasourceReleaseOutputFolder, "temporal-characterization.csv")

Achilles::getTemporalData(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = cdmDatabaseSchema,
    resultsDatabaseSchema = resultsDatabaseSchema,
  )

Achilles::performTemporalCharacterization(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  outputFile = outputFile
)

# Augment concept files with data quality details
AresIndexer::augmentConceptFiles(releaseFolder = file.path(aresDataRoot, releaseKey))

# Get a list of sources generated by the exportToAres function
sourceFolders <- list.dirs(aresDataRoot, recursive = FALSE)


AresIndexer::buildNetworkIndex(sourceFolders = sourceFolders, outputFolder = aresDataRoot)
AresIndexer::buildDataQualityIndex(sourceFolders = sourceFolders, outputFolder = aresDataRoot)
AresIndexer::buildNetworkUnmappedSourceCodeIndex(sourceFolders = sourceFolders, outputFolder = aresDataRoot)

