#!/bin/bash

# Check for environment (dev or prod)
if [ "$1" == "dev" ]; then
    AWS_ACCOUNT_ID="500206249851"
elif [ "$1" == "prod" ]; then
    AWS_ACCOUNT_ID="063312575449" # Replace with your prod AWS account ID
else
    echo "Usage: $0 [dev|prod]"
    exit 1
fi

docker build --platform=linux/amd64 \
-t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/pgadmin-readonly \
--no-cache \
.
