#!/bin/bash


docker run -p 80:80 --read-only=true \
    -e 'PGADMIN_DEFAULT_EMAIL=mhmcb@umsytem.edu' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -e 'PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True' \
    -e 'PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"' \
    -e 'PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10' \
    500206249851.dkr.ecr.us-east-2.amazonaws.com/pgadmin-readonly