

-- GRANT ALL ON SCHEMA
GRANT ALL ON ALL SCHEMAS IN DATABASE ATLAS_MU_DEV TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ATLAS_MU_DEV TO ROLE OMOP_ATLAS;

GRANT ALL ON ALL TABLES IN DATABASE ATLAS_MU_DEV TO ROLE OMOP_ATLAS;
GRANT ALL ON FUTURE TABLES IN DATABASE ATLAS_MU_DEV TO ROLE OMOP_ATLAS;