begin
use tracs_cdm;

TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_PERSON;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_OBSERVATION_PERIOD;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_SPECIMEN;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_DEATH;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_VISIT_OCCURRENCE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_VISIT_DETAIL;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_PROCEDURE_OCCURRENCE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_DRUG_EXPOSURE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_DEVICE_EXPOSURE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_CONDITION_OCCURRENCE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_MEASUREMENT;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_NOTE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_NOTE_NLP;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_OBSERVATION;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_FACT_RELATIONSHIP;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_LOCATION;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_CARE_SITE;
TRUNCATE TABLE TRACS_CDM.OMOP.ZBU_PROVIDER;
end;
