library(DatabaseConnector)
library(SqlRender)
library(Achilles)
library(DataQualityDashboard)
library(AresIndexer)
library(keyring)
options(connectionObserver = NULL)

cdmDatabaseSchema = "cdm"
resultsDatabaseSchema = "results" # used to store Achilles output
vocabDatabaseSchema = "cdm" #usually located within the cdm schema
numThreads = 4
cdmSourceName = 'MU'
cdmVersion = "5.4"

aresDataDirectory = "./data" #Achilles output directory

# Build JDBC connection string
CONNECTION_STRING <- paste0(
  "jdbc:snowflake://", "fp20843.us-east-2.aws", 
  ".snowflakecomputing.com/?db=", "ATLAS_MU_PROD",
  "&schema=", "RESULTS",
  "&warehouse=", "OMOP_ETL_WH", 
  "&role=", "OMOP_ELT", 
  "&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true",
  "&private_key_file=", "./WebAPI/.settings/dev/rsa_key.p8",
  "&private_key_file_pwd=", "<pubkey>",
)

keyring::key_set_with_value("connectionString", password = CONNECTION_STRING)
keyring::key_set_with_value("user", password = "SERVICE_USER_ATLAS")
keyring::key_set_with_value("password", password = "secret")

# Create connection details directly using credentials
connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = "snowflake", 
  server = "",
  connectionString = keyring::key_get("connectionString"),
  user = keyring::key_get("user"),
  password = keyring::key_get("password"),
  pathToDriver = "./drivers/"
)


# Run Achilles
Achilles::achilles(
  connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema ,
  resultsDatabaseSchema= resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  numThreads = 1,
  cdmVersion = cdmVersion,
  createIndices = F,
  createTable = T,
  smallCellCount = 0,
)


# Export Achilles results to Ares supported format
Achilles::exportToAres(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  outputPath = aresDataDirectory,
)

sourceReleaseKey = AresIndexer::getSourceReleaseKey(connectionDetails, cdmDatabaseSchema)
datasourceReleaseOutputFolder <- file.path(aresDataDirectory, sourceReleaseKey)

#Run data quality checks
tablesToExclude <- c("COHORT_DEFINITION","CONCEPT", "VOCABULARY", "CONCEPT_ANCESTOR", "CONCEPT_RELATIONSHIP", "CONCEPT_CLASS", "CONCEPT_SYNONYM", "RELATIONSHIP", "DOMAIN")
DataQualityDashboard::executeDqChecks(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  vocabDatabaseSchema = vocabDatabaseSchema,
  cdmSourceName = cdmSourceName,
  numThreads = numThreads,
  outputFolder = datasourceReleaseOutputFolder,
  outputFile = "dq-result.json",
  verboseMode = T,
  writeToTable = F,
  tablesToExclude = tablesToExclude,
  cdmVersion = cdmVersion

)
# Run Achilles temporal characterization
outputFile <- file.path(datasourceReleaseOutputFolder, "temporal-characterization.csv")

Achilles::performTemporalCharacterization(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  resultsDatabaseSchema = resultsDatabaseSchema,
  outputFile = outputFile,
)

# Get a list of sources generated by the exportToAres function
list <- list.dirs(aresDataDirectory, recursive = FALSE)

# Augment concept files with data quality details
AresIndexer::augmentConceptFiles(releaseFolder = file.path(aresDataDirectory, sourceReleaseKey))

# Export index of all sql functions used in data processing
AresIndexer::buildExportQueryIndex(aresDataDirectory)

AresIndexer::buildNetworkIndex(sourceFolders = list, outputFolder = aresDataDirectory)
AresIndexer::buildDataQualityIndex(sourceFolders = list, outputFolder = aresDataDirectory)
AresIndexer::buildNetworkUnmappedSourceCodeIndex(sourceFolders = list, outputFolder = aresDataDirectory)

