COPY INTO OMOP_CDM.VOCABULARY.DRUG_STRENGTH
  FROM @PCORNET_CDM.staging.aws_stage
  PATTERN = '.*DRUG_STRENGTH.*'
  FILE_FORMAT = (FORMAT_NAME = csv_files);

 COPY INTO OMOP_CDM.VOCABULARY.CONCEPT_SYNONYM
  FROM @PCORNET_CDM.staging.aws_stage
  PATTERN = '.*CONCEPT_SYNONYM.*'
  FILE_FORMAT = (FORMAT_NAME = csv_files);

   COPY INTO OMOP_CDM.VOCABULARY.CONCEPT
  FROM @PCORNET_CDM.staging.aws_stage
  PATTERN = '.*CONCEPT.csv'
  FILE_FORMAT = (FORMAT_NAME = csv_files);

   COPY INTO OMOP_CDM.VOCABULARY.CONCEPT_ANCESTOR
  FROM @PCORNET_CDM.staging.aws_stage
  PATTERN = '.*CONCEPT_ANCESTOR.*'
  FILE_FORMAT = (FORMAT_NAME = csv_files);

   COPY INTO OMOP_CDM.VOCABULARY.CONCEPT_RELATIONSHIP
  FROM @PCORNET_CDM.staging.aws_stage
  PATTERN = '.*CONCEPT_RELATIONSHIP.*'
  FILE_FORMAT = (FORMAT_NAME = csv_files);