-- WHEN OMOP UPDATED  RUN:
drop table if exists tracs_cdm.XOMOP.XSTG_OMOP_HARVEST;
select 
	getdate() as BUILD_DATE ,
	harvest.refresh_demographic_date as DATA_REFRESH_DATE
	into TRACS_CDM.XOMOP.XSTG_OMOP_HARVEST
from TRACS_CDM.PCDM.HARVEST;

ALTER TABLE TRACS_CDM.[XOMOP].[XSTG_OMOP_HARVEST] REBUILD WITH (DATA_COMPRESSION=PAGE);
