-- BEGIN WRITE --
USE TRACS_CDM;

exec SP_RENAME 'XOMOP.ZBU_COHORT_OMOP', 'XSTG_COHORT_OMOP';
exec SP_RENAME 'XOMOP.ZBU_OMOP_HARVEST', 'XSTG_OMOP_HARVEST';

exec SP_RENAME 'OMOP.ZBU_PERSON', 'XSTG_PERSON';
exec SP_RENAME 'OMOP.ZBU_OBSERVATION_PERIOD', 'XSTG_OBSERVATION_PERIOD';
exec SP_RENAME 'OMOP.ZBU_SPECIMEN', 'XSTG_SPECIMEN' ;
exec SP_RENAME 'OMOP.ZBU_DEATH', 'XSTG_DEATH' ;
exec SP_RENAME 'OMOP.ZBU_VISIT_OCCURRENCE', 'XSTG_VISIT_OCCURRENCE' ;
exec SP_RENAME 'OMOP.ZBU_VISIT_DETAIL', 'XSTG_VISIT_DETAIL' ;
exec SP_RENAME 'OMOP.ZBU_PROCEDURE_OCCURRENCE', 'XSTG_PROCEDURE_OCCURRENCE' ;
exec SP_RENAME 'OMOP.ZBU_DRUG_EXPOSURE', 'XSTG_DRUG_EXPOSURE' ;
exec SP_RENAME 'OMOP.ZBU_DEVICE_EXPOSURE', 'XSTG_DEVICE_EXPOSURE' ;
exec SP_RENAME 'OMOP.ZBU_CONDITION_OCCURRENCE', 'XSTG_CONDITION_OCCURRENCE' ;
exec SP_RENAME 'OMOP.ZBU_MEASUREMENT', 'XSTG_MEASUREMENT' ;
-- END WRITE --
-- BEGIN WRITE --
USE TRACS_CDM;
exec SP_RENAME 'OMOP.ZBU_NOTE', 'XSTG_NOTE' ;
exec SP_RENAME 'OMOP.ZBU_NOTE_NLP', 'XSTG_NOTE_NLP' ;
exec SP_RENAME 'OMOP.ZBU_OBSERVATION', 'XSTG_OBSERVATION' ;
exec SP_RENAME 'OMOP.ZBU_FACT_RELATIONSHIP', 'XSTG_FACT_RELATIONSHIP' ;

exec SP_RENAME 'OMOP.ZBU_LOCATION', 'XSTG_LOCATION' ;
exec SP_RENAME 'OMOP.ZBU_CARE_SITE', 'XSTG_CARE_SITE' ;
exec SP_RENAME 'OMOP.ZBU_PROVIDER', 'XSTG_PROVIDER' ;

exec SP_RENAME 'OMOP.ZBU_DRUG_ERA', 'XSTG_DRUG_ERA' ;
exec SP_RENAME 'OMOP.ZBU_DOSE_ERA', 'XSTG_DOSE_ERA' ;
exec SP_RENAME 'OMOP.ZBU_CONDITION_ERA', 'XSTG_CONDITION_ERA' ;

exec SP_RENAME 'OMOP.ZBU_COHORT', 'XSTG_COHORT' ;
exec SP_RENAME 'OMOP.ZBU_COHORT_ATTRIBUTE', 'XSTG_COHORT_ATTRIBUTE' ;
-- END WRITE --
