-- BEGIN WRITE --
USE TRACS_CDM;

exec SP_RENAME 'XOMOP.XSTG_COHORT_OMOP', 'COHORT_OMOP';
exec SP_RENAME 'XOMOP.XSTG_OMOP_HARVEST', 'OMOP_HARVEST';

exec SP_RENAME 'OMOP.XSTG_PERSON', 'PERSON';
exec SP_RENAME 'OMOP.XSTG_OBSERVATION_PERIOD', 'OBSERVATION_PERIOD';
exec SP_RENAME 'OMOP.XSTG_SPECIMEN', 'SPECIMEN' ;
exec SP_RENAME 'OMOP.XSTG_DEATH', 'DEATH' ;
exec SP_RENAME 'OMOP.XSTG_VISIT_OCCURRENCE', 'VISIT_OCCURRENCE' ;
exec SP_RENAME 'OMOP.XSTG_VISIT_DETAIL', 'VISIT_DETAIL' ;
exec SP_RENAME 'OMOP.XSTG_PROCEDURE_OCCURRENCE', 'PROCEDURE_OCCURRENCE' ;
exec SP_RENAME 'OMOP.XSTG_DRUG_EXPOSURE', 'DRUG_EXPOSURE' ;
exec SP_RENAME 'OMOP.XSTG_DEVICE_EXPOSURE', 'DEVICE_EXPOSURE' ;
exec SP_RENAME 'OMOP.XSTG_CONDITION_OCCURRENCE', 'CONDITION_OCCURRENCE' ;
exec SP_RENAME 'OMOP.XSTG_MEASUREMENT', 'MEASUREMENT' ;
-- END WRITE --
-- BEGIN WRITE --
USE TRACS_CDM;
exec SP_RENAME 'OMOP.XSTG_NOTE', 'NOTE' ;
exec SP_RENAME 'OMOP.XSTG_NOTE_NLP', 'NOTE_NLP' ;
exec SP_RENAME 'OMOP.XSTG_OBSERVATION', 'OBSERVATION' ;
exec SP_RENAME 'OMOP.XSTG_FACT_RELATIONSHIP', 'FACT_RELATIONSHIP' ;

exec SP_RENAME 'OMOP.XSTG_LOCATION', 'LOCATION' ;
exec SP_RENAME 'OMOP.XSTG_CARE_SITE', 'CARE_SITE' ;
exec SP_RENAME 'OMOP.XSTG_PROVIDER', 'PROVIDER' ;

exec SP_RENAME 'OMOP.XSTG_DRUG_ERA', 'DRUG_ERA' ;
exec SP_RENAME 'OMOP.XSTG_DOSE_ERA', 'DOSE_ERA' ;
exec SP_RENAME 'OMOP.XSTG_CONDITION_ERA', 'CONDITION_ERA' ;

exec SP_RENAME 'OMOP.XSTG_COHORT', 'COHORT' ;
exec SP_RENAME 'OMOP.XSTG_COHORT_ATTRIBUTE', 'COHORT_ATTRIBUTE' ;

-- END WRITE --
