use database atlas_mu_prod;
use schema cdm;
use role omop_elt;
use warehouse omop_etl_wh;

drop table care_site;
drop table condition_era;
drop table condition_occurence;
drop table death;
drop table drug_exposure;
drop table location;
drop table measurement;
drop table observation_period;
drop table observation;
drop table person;
drop table procedure_occurrence;
drop table provider;
drop table visit_occurrence;

CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CDM_SOURCE clone ATLAS_MU_DEV.CDM.CDM_SOURCE;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.COHORT_DEFINITION clone ATLAS_MU_DEV.CDM.COHORT_DEFINITION;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT clone ATLAS_MU_DEV.CDM.CONCEPT;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT_ANCESTOR clone ATLAS_MU_DEV.CDM.CONCEPT_ANCESTOR;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT_CLASS clone ATLAS_MU_DEV.CDM.CONCEPT_CLASS;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT_CPT4 clone ATLAS_MU_DEV.CDM.CONCEPT_CPT4;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT_RELATIONSHIP clone ATLAS_MU_DEV.CDM.CONCEPT_RELATIONSHIP;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.CONCEPT_SYNONYM clone ATLAS_MU_DEV.CDM.CONCEPT_SYNONYM;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.DOMAIN clone ATLAS_MU_DEV.CDM.DOMAIN;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.DRUG_STRENGTH clone ATLAS_MU_DEV.CDM.DRUG_STRENGTH;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.RELATIONSHIP clone ATLAS_MU_DEV.CDM.RELATIONSHIP;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.SOURCE_TO_CONCEPT_MAP clone ATLAS_MU_DEV.CDM.SOURCE_TO_CONCEPT_MAP;
CREATE OR REPLACE TABLE ATLAS_MU_PROD.CDM.VOCABULARY clone ATLAS_MU_DEV.CDM.VOCABULARY;

CREATE OR REPLACE SCHEMA ATLAS_MU_PROD.CROSSWALK clone ATLAS_MU_DEV.CROSSWALK;

CREATE OR REPLACE SCHEMA ATLAS_MU_PROD.CROSSWALK clone ATLAS_MU_DEV.CROSSWALK;