create schema CROSSWALK;

CREATE TABLE OMOP_CDM.CROSSWALK.GENDER_XWALK 
(
  CDM_NAME character varying(100 ) 
, CDM_TBL character varying(100 ) 
, SRC_GENDER character varying(20 ) 
, FHIR_CD character varying(100 ) 
, TARGET_CONCEPT_ID integer NOT NULL 
, TARGET_CONCEPT_NAME character varying(255 ) NOT NULL 
, TARGET_DOMAIN_ID character varying(20 ) NOT NULL 
, TARGET_VOCABULARY_ID character varying(20 ) NOT NULL 
, TARGET_CONCEPT_CLASS_ID character varying(20 ) NOT NULL 
, TARGET_STANDARD_CONCEPT character varying(1 ) 
, TARGET_CONCEPT_CODE character varying(50 ) NOT NULL 
) ;

Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','M','male',8507,'MALE','Gender','Gender','Gender','S','M');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','other',0,'Other','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','unknown',0,'Unknown','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:M','male',8507,'Male','Gender','Gender','Gender','S','M');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:F','female',8532,'FEMALE','Gender','Gender','Gender','S','F');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:NI','unknown',0,'No Information','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:O','Other',0,'Other','Gender','Gender','Gender','S','0');
Insert into OMOP_CDM.CROSSWALK.GENDER_XWALK  (CDM_NAME,CDM_TBL,SRC_GENDER,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|SEX:A',null,0,'Ambiguous','Gender','Gender','Gender','S','0');

CREATE TABLE OMOP_CDM.CROSSWALK.ETHNICITY_XWALK
(
  CDM_NAME character varying(100 ) 
, CDM_TBL character varying(100 ) 
, SRC_ETHNICITY character varying(100 ) 
, FHIR_CD character varying(100 ) 
, TARGET_CONCEPT_ID integer NOT NULL 
, TARGET_CONCEPT_NAME character varying(255 ) NOT NULL 
, TARGET_DOMAIN_ID character varying(20 ) NOT NULL 
, TARGET_VOCABULARY_ID character varying(20 ) NOT NULL 
, TARGET_CONCEPT_CLASS_ID character varying(20 ) NOT NULL 
, TARGET_STANDARD_CONCEPT character varying(1 ) 
, TARGET_CONCEPT_CODE character varying(50 ) NOT NULL 
) 
;
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:NI','No Information',0,'No Information','Ethnicity','Ethnicity','Ethnicity','S','NI');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','Y','2135-2',38003563,'Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Hispanic');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','N','2186-5',38003564,'Not Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Not Hispanic');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','No Information',0,'No Information','Ethnicity','Ethnicity','Ethnicity','S','NI');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','Other',0,'Other','Ethnicity','Ethnicity','Ethnicity','S','OT');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','R','Refuse to answer',0,'Refuse to answer','Ethnicity','Ethnicity','Ethnicity','S','R');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','Unknown',0,'Unknown','Ethnicity','Ethnicity','Ethnicity','S','UN');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:Y','2135-2',38003563,'Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Hispanic');
Insert into OMOP_CDM.CROSSWALK.ETHNICITY_XWALK (CDM_NAME,CDM_TBL,SRC_ETHNICITY,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|HISP:N','2186-5',38003564,'Not Hispanic or Latino','Ethnicity','Ethnicity','Ethnicity','S','Not Hispanic');

--Race
CREATE TABLE OMOP_CDM.CROSSWALK.RACE_XWALK
(
  CDM_NAME character varying(100 ) 
, CDM_TBL character varying(100 ) 
, SRC_RACE character varying(100 ) 
, FHIR_CD character varying(100 ) 
, TARGET_CONCEPT_ID integer NOT NULL 
, TARGET_CONCEPT_NAME character varying(255 ) NOT NULL 
, TARGET_DOMAIN_ID character varying(20 ) NOT NULL 
, TARGET_VOCABULARY_ID character varying(20 ) NOT NULL 
, TARGET_CONCEPT_CLASS_ID character varying(20 ) NOT NULL 
, TARGET_STANDARD_CONCEPT character varying(1 ) 
, TARGET_CONCEPT_CODE character varying(50 ) NOT NULL 
) 
;

Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','06','2131-1',45878142,'Other-multiple race','Race','Race','Race','S','6');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','01','1002-5',8657,'American  Indian  or  Alaska  Native','Race','Race','Race','S','1');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','02','2028-9',8515,'Asian','Race','Race','Race','S','2');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','03','2054-5',8516,'Black  or  African  American','Race','Race','Race','S','3');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','04','2076-8',8557,'Native  Hawaiian  or  Other  Pacific  Islander','Race','Race','Race','S','4');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','05','2106-3',8527,'White','Race','Race','Race','S','5');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','07',null,0,'Refused to Answer','Race','Race','Race','S','7');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','UN','Unknown',45877986,'Unknown','Race','Race','Race','S','UN');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','OT','Other',45878142,'Other','Race','Race','Race','S','OT');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','DEMOGRAPHIC','NI','NI',46237210,'NI','Race','Race','Race','S','NI');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:NA','1002-5',8657,'American  Indian  or  Alaska  Native','Race','Race','Race','S','NA');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:AS','2028-9',8515,'Asian','Race','Race','Race','S','AS');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:B','2054-5',8516,'Black  or  African  American','Race','Race','Race','S','B');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:H','2076-8',8557,'Native  Hawaiian  or  Other  Pacific  Islander','Race','Race','Race','S','H');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:W','2106-3',8527,'White','Race','Race','Race','S','W');
Insert into OMOP_CDM.CROSSWALK.RACE_XWALK (CDM_NAME,CDM_TBL,SRC_RACE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','PATIENT_DIMENSION','DEM|RACE:NI','0',46237210,'NI','Race','Race','Race','S','NI');